name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate PR
    uses: whisller/forge-ci/.github/workflows/forge-ci-go-validate-pr.yml@main
    with:
      go-version: '1.23'
      use-golangci-lint: true
      golangci-lint-version: 'v1.62'
      coverage-threshold: 80
      run-test: true
      run-build: true
